# Generated by Django 4.1.7 on 2023-03-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_remove_comment_commentpost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Content',
        ),
    ]
