# Generated by Django 4.1.7 on 2023-03-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_category_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='oneNews',
            new_name='OneNews',
        ),
    ]
