# Generated by Django 4.1.7 on 2023-03-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_onenews_news_onenews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='OneNews',
            new_name='header',
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
