# Generated by Django 4.1.7 on 2023-03-12 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_delete_content_rename_onenews_news_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
